config/routes.rb
Rails.application.routes.draw do
 
  

  namespace :admin do
  get 'users/index'
  end

  namespace :admin do
  get 'users/show'
  end

  root to: "home#index"  

  mount RailsAdmin::Engine => '/dashboard', as: 'rails_admin'
  
  devise_for :admins

  namespace :admin do # Added this configuration so admin goes to admin/client when creating a new client instead of going to client home page
    resources :clients
    resources :users, only: [:index, :show]
  end

  devise_for :clients
  devise_for :users

  resources :clients do
    resources :kontests, shallow: true
  end

  get '/user/' => 'users#show', as: :user_show
  get '/user/edit' => 'users#edit',  as: :edit_user
  patch '/user' => 'users#update', as: :user_update
  get '/registercode' => 'users#registercode', as: :registercode
  post '/registercode' => 'users#addcode', as: :add_code
  get '/result' => 'users#result', as: :result
  get '/registeredcodes' => 'users#registeredcodes', as: :registeredcodes

  get '/homeadmin' => 'homeadmin#index', as: :indexadmin
  get '/homeuser' => 'homeuser#index', as: :indexuser
  get '/homeclient' => 'homeclient#index', as: :indexclient
  
  

  
    
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :kontestusers
   has_many :kontests, :through => :kontestusers      
   
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
   @users = User.all
  end

  def show
   @user = User.find params[:id]
  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    binding.pry
  end

  def show
   @user = current_user
  end

  def edit
     @user = current_user
  end

  def update
     @user = current_user     
     if @user.update_attributes user_params
        redirect_to user_show_path(@user)
     else
      render :edit
     end
  end

  def registercode
   # @user = current_user
  end

  def addcode
     kontestcode = code_params
     kontest = Kontest.where(kontestcode: kontestcode[0])[0]
     if kontest
        unicode = Unicode.where(secuence: kontestcode[1])[0]
     
        if unicode 
          if unicode.user_id == nil
            # If code NOT registered yet
              unicode.user_id = current_user.id 
              unicode.registrationdate = Time.now 
              if unicode.save
                 if unicode.winner  # If winner
                    session[:award] = kontest.award
                    flash[:message] = "1"     
                    current_user.kontests << kontest
                    redirect_to result_path(current_user)    
                 else   # If NOT Winner
                    session[:award] = kontest.award
                    flash[:message] = "2"      
                    current_user.kontests << kontest
                    redirect_to result_path(current_user) 
                 end
              else   # If does NOT save
                 flash[:message] = "Error, por favor ingreasr codigo nuevamente"
                 render :registercode            
              end    
          else  # If code registered by user
              if unicode.user_id == current_user.id
                 flash[:message] = "3"      
                 redirect_to result_path(current_user)      
              else   # If code registered by another user    
                 flash[:message] = "4"      
                 redirect_to result_path(current_user)   
              end
          end         
        else  # If wrong UNICODE
           flash[:message] = "5"      
           redirect_to result_path(current_user)
        end
     else   # If wrong Kontest Code
        flash[:message] = "6"
        redirect_to result_path(current_user)
     end
   
  end  # Closes Addcode


  def registeredcodes
    @user_unicodes = []
    @kontests = current_user.kontests.uniq
    @kontests.each do |kontest|
      kontest.unicodes.each do |unicode|
         if unicode.user_id == current_user.id
            @user_unicodes << unicode
         end
        
      end       
    end  
    
    
  end



  private

  def user_params
   params.require(:user).permit(:nombre,:apellido,:email,:edad,:genero,:celular,:direccion,:pais,:ciudad)
  end

  def code_params
    form = []
    form << params[:kontestcode]
    form << params[:unicode]
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Users#edit</h1>

<br>

<% if @user.errors.any? %>
   <% @user.errors.full_messages.each do |error|%>
   <p class="text-danger">
      <%= error%>
   </p>
   <% end %>
<% end %>



<div class="container-fluid">
   
   <div class="col-sm-6">
      <div class="panel panel-default">
         <div class="panel-heading">
            <h3 class="panel-title">Editar Usuario</h3>
         </div>
         <div class="panel-body">

            <%= form_for @user, url: user_update_path do |f| %>
               
               <div class="col-sm-6">
                  <%= f.label :nombre %> <%= f.text_field :nombre, :class => "form-control" %>
               <%= f.label :apellido %> <%= f.text_field :apellido, :class => "form-control" %>
               <%= f.label :email %> <%= f.text_field :email, :class => "form-control" %>
               <%= f.label :edad %> <%= f.text_field :edad, :class => "form-control" %>
               <%= f.label :genero %> <%= f.text_field :genero, :class => "form-control" %>   
               </div>
               <div class="col-sm-6">
                  <%= f.label :celular %> <%= f.text_field :celular, :class => "form-control" %>
               <%= f.label :direccion %> <%= f.text_field :direccion, :class => "form-control" %>
               <%= f.label :pais %> <%= f.text_field :pais, :class => "form-control" %>
               <%= f.label :ciudad %> <%= f.text_field :ciudad, :class => "form-control" %>   
               <hr>
               <%= f.submit "Aceptar Cambios", :class => "btn btn-primary" %> 
               </div>
               
               
                 
                  

            <% end %>


         </div> <!--Panel-body -->
      </div>  <!--Panel-default -->
   </div> <!-- Col sm 6 -->

   
  

   <%= link_to "Inicio", user_show_path(@user) ,:class => "btn btn-default" %>


</div>   <!-- Container -->

app/views/users/registercode.html.erb
<br>
<div class="container-fluid">
   
   <div class="col-sm-6">
      <div class="panel panel-default">
         <div class="panel-heading">
            <h3 class="panel-title">Ingresar Codigo</h3>
         </div>
         <div class="panel-body">
            <%= form_tag '/registercode' do %>
               <%= label_tag(:kontestcode, "Codigo:") %><%= text_field_tag :kontestcode  %> -
               <%= text_field_tag :unicode  %>
   
               <%= submit_tag("Enviar") %>
            <% end %>

            <hr>
            <%= link_to "Regresar", root_path, :class => "btn btn-default" %>

         </div>
      </div>
   </div>
</div>

app/views/users/registeredcodes.html.erb
<br>
<div class="container-fluid">
   
   <div class="col-sm-6">
      <div class="panel panel-default">
         <div class="panel-heading">
            <h3 class="panel-title">Marcas en las que haz participado</h3>
         </div>
         <div class="panel-body">

            <% @kontests.each do |kontest| %>
               <p><%= kontest.clientname %></p>
            <% end %>
               
            <hr>

            <% @user_unicodes.each do |unicode| %>
               <% @kontests.each do |kontest| %>
                  <% if kontest.id == unicode.kontest_id %>
                     <p><%= kontest.clientname %>
                  <% end %>
               <% end %>
                - <%= unicode.secuence %> - Puntos aquiridos en Kontest: 3</p>
               
            <% end %>

            <hr>
            <%= link_to "Regresar", root_path, :class => "btn btn-default" %>
         </div>

      </div>
   </div>

</div>

app/views/users/result.html.erb
<br>
<div class="container-fluid">
   
   
      <div class="col-sm-6">
         <div class="panel panel-default">
            <div class="panel-heading">
               <h3 class="panel-title">Mensaje</h3>
            </div>
            <div class="panel-body">
               <% if flash[:message] == "1" %>
                  <p>Ganaste un: </p>
                  <p><%= session[:award] %></p>
                  <%= link_to "Ir a Inicio", root_path, :class => "btn btn-default" %>
               <% elsif  flash[:message] == "2" %>
                  <p>NO Ganaste, Sigue Intentando para ganar un: </p>
                  <p>   <%= session[:award] %></p>
                  <%= link_to "Ingresar Otro Codigo", registercode_path, :class => "btn btn-default" %>   
               <% elsif  flash[:message] == "3" %>
                  <p>Codigo ya registrado</p>
                  <%= link_to "Ingresar Otro Codigo", registercode_path, :class => "btn btn-default" %>   
               <% elsif  flash[:message] == "4" %>
                  <p>Codigo ya registrado por otro usuario, Enviar foto de codigo y comunicarse con soporte</p>
                  <%= link_to "Help", registercode_path, :class => "btn btn-default" %>   
               <% elsif  flash[:message] == "5" %>
                  <p>Codigo no registrado, ingrese codigo correctamente 2</p>
                  <%= link_to "Ingresar Codigo Nuevamente", registercode_path, :class => "btn btn-default" %>      
               <% elsif  flash[:message] == "6" %>
                  <p>Codigo no registrado, ingrese codigo correctamente 1</p>
                  <%= link_to "Ingresar Codigo Nuevamente", registercode_path, :class => "btn btn-default" %>         
                  
               <% end %>            
            </div>
         </div>
      </div>
   


</div>

app/views/users/show.html.erb
<h1>Perfil de Usuario</h1>


<div class="container-fluid">
   <div class="col-sm-9">
         <div class="panel panel-default">
            <div class="panel-heading">
               <h2 class="panel-title text-left"><%= @user.nombre %> 
                  <%= link_to "Editar perfil", edit_user_path(@user) , :class => "btn btn-default" %>
                  <%= link_to "Menu Principal", indexuser_path(@user) , :class => "btn btn-default" %>
               </h2>   
            </div>
            <div class="panel-body">
               <div class="row">
                  <div class="col-sm-6">                     
                     <table class="table table-bordered">
                        <tr><th scope="row">Nombre:</th><td><%= @user.nombre %></td></tr>
                        <tr><th scope="row">Apellido:</th><td><%= @user.apellido   %> </td></tr>
                        <tr><th scope="row">Email:</th><td><%= @user.email %></td></tr>
                        <tr><th scope="row">Edad:</th><td><%= @user.edad   %> </td></tr>
                        <tr><th scope="row">Genero:</th><td><%= @user.genero   %> </td></tr>
                     </table>
                  </div> 
                  <div class="col-sm-6">                     
                     <table class="table table-bordered">
                        <tr><th scope="row">Celular:</th><td><%= @user.celular   %> </td></tr>
                        <tr><th scope="row">Direccion:</th><td><%= @user.direccion   %> </td></tr>
                        <tr><th scope="row">Pais:</th><td><%= @user.pais   %> </td></tr>
                        <tr><th scope="row">Ciudad:</th><td><%= @user.ciudad   %> </td></tr>
                        <tr><th scope="row">Puntos Acumulados:</th><td><%= @user.puntos   %> </td></tr>
                     </table>
                  </div>
               </div>               

            </div> <!--Panel-body -->
      </div>  <!--Panel-default -->
   </div> <!-- Col sm 9 -->
      
   


</div> <!-- Container -->   