config/routes.rb
Rails.application.routes.draw do
 
  

  namespace :admin do
  get 'users/index'
  end

  namespace :admin do
  get 'users/show'
  end

  root to: "home#index"  

  mount RailsAdmin::Engine => '/dashboard', as: 'rails_admin'
  
  devise_for :admins

  namespace :admin do # Added this configuration so admin goes to admin/client when creating a new client instead of going to client home page
    resources :clients
    resources :users, only: [:index, :show]
  end

  devise_for :clients
  devise_for :users

  resources :clients do
    resources :kontests, shallow: true
  end

  get '/user/' => 'users#show', as: :user_show
  get '/user/edit' => 'users#edit',  as: :edit_user
  patch '/user' => 'users#update', as: :user_update
  get '/registercode' => 'users#registercode', as: :registercode
  post '/registercode' => 'users#addcode', as: :add_code
  get '/result' => 'users#result', as: :result
  get '/registeredcodes' => 'users#registeredcodes', as: :registeredcodes

  get '/homeadmin' => 'homeadmin#index', as: :indexadmin
  get '/homeuser' => 'homeuser#index', as: :indexuser
  get '/homeclient' => 'homeclient#index', as: :indexclient
  
  

  
    
  
  

end

app/models/client.rb
class Client < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :kontests, dependent: :destroy         

   

end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < ApplicationController
    before_action :authenticate_admin!

  
  def create
   @client = Client.new client_params
      
   if @client.save
      redirect_to client_path(@client)
   else
      render "clients/new"
   end
  end


  def update
     @client = Client.find params[:id]
     if @client.update_attributes client_params
        redirect_to client_path(@client)
     else
        render :edit
     end
  end


  private

  def client_params
   params.require(:client).permit(:name,:password ,:email,:contacto,:celular,:telefono,:comentarios,:direccion,:codigo,:pais,:ciudad,:logo)
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_admin!

  def index
   @clients = Client.all
  end

  def new
    @client = Client.new
  end

  def show
    @client = Client.find params[:id]
    @kontests = Kontest.where(client_id: @client.id )
  end

  def edit
    @client = Client.find params[:id]
  end



  private

  def client_params
   params.require(:client).permit(:name,:email,:contacto,:celular,:telefono,:comentarios,:direccion,:codigo,:pais,:ciudad,:logo)
  end


end


  
      

app/helpers/admin/clients_helper.rb
module Admin::ClientsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/edit.html.erb
<%= render "layouts/menu" %>

<% if @client.errors.any? %>
   <% @client.errors.full_messages.each do |error|%>
   <p class="text-danger">
      <%= error%>
   </p>
   <% end %>
<% end %>

<div class="container-fluid">

   <div class="col-sm-6">
      <div class="panel panel-default">
         <div class="panel-heading">
            <h3 class="panel-title">Editar Cliente</h3>
         </div>

         <div class="panel-body">
            <%= form_for [:admin, @client] do |f| %> <!-- Sends to admin/clients#create-->
               <div class="col-sm-6">
                   <%= f.label :name, "Nombre del Cliente" %> <%= f.text_field :name, :class => "form-control" %>   
                   
                   <%= f.label :comentarios %> <%= f.text_field :comentarios, :class => "form-control" %>
                   <%= f.label :pais %> <%= f.text_field :pais, :class => "form-control" %>
                   <%= f.label :ciudad %> <%= f.text_field :ciudad, :class => "form-control" %>
                   <%= f.label :logo %> <%= f.text_field :logo, :class => "form-control" %>
                  <hr>
                  <%= f.submit "Aceptar Cambios", :class => "btn btn-primary" %>
               
               </div>
               <div class="col-sm-6">
                  <%= f.label :email %> <%= f.text_field :email, :class => "form-control" %> 
                  <%= f.label :contacto %> <%= f.text_field :contacto, :class => "form-control" %>
                  <%= f.label :celular %> <%= f.text_field :celular, :class => "form-control" %>
                  <%= f.label :telefono %> <%= f.text_field :telefono, :class => "form-control" %>
                  <%= f.label :direccion %> <%= f.text_field :direccion, :class => "form-control" %>
               </div> 
               
                
               
            <% end %>          
         </div> <!--Panel-body -->
      </div>  <!--Panel-default -->
   </div> <!--Panel-body -->

   <%= link_to "Inicio", root_path,:class => "btn btn-default" %>

</div>   <!-- Container -->

app/views/clients/index.html.erb
<%= render "layouts/menu" %>

<div class="container-fluid">
   

   <div class="col-sm-6">

      <div class="panel panel-default">
         <div class="panel-heading">
            <h3 class="panel-title">Lista de Clientes para el Admin</h3>
         </div>
         <div class="panel-body">
            <%= link_to "Home", "/homeadmin" , :class => "btn btn-default" %>
            <%= link_to "Nuevo Cliente", new_client_path , :class => "btn btn-default" %>
            <table class="table table-bordered">
            <hr>

               <tr>
                  <th>Cliente</th>
                  <th>Contacto</th>
                  <th>Email</th>
                  <th>Celular</th>
               </tr>
               <% @clients.each do |client| %>
               <tr>
                     <td><%= link_to client.name, client_path(client) %></td>
                     <td><%= client.contacto %></td>
                     <td><%= client.email %></td>
                     <td><%= client.celular %> </td>
               </tr>               
               <% end %>
            </table>         

         </div> <!-- Panel-body -->
      </div>   <!-- Panel-default -->
      
   </div>       <!-- Col-sm-6 -->
   

</div>    <!-- Container -->

app/views/clients/new.html.erb
<%= render "layouts/menu" %>

<% if @client.errors.any? %>
   <% @client.errors.full_messages.each do |error|%>
   <p class="text-danger">
      <%= error%>
   </p>
   <% end %>
<% end %>
<div class="container-fluid">
   
   <div class="col-sm-6">
      <div class="panel panel-default">
         <div class="panel-heading">
            <h3 class="panel-title">Crear Cliente</h3>
         </div>
         <div class="panel-body">
            <%= form_for [:admin, @client] do |f| %> <!-- Sends to admin/clients#create-->
               <div class="col-sm-6">
                   <%= f.label :name, "Nombre del Cliente" %> <%= f.text_field :name, :class => "form-control" %>   
                   <%= f.label :password %> <%= f.text_field :password, :class => "form-control" %> 
                   <%= f.label :comentarios %> <%= f.text_field :comentarios, :class => "form-control" %>
                   <%= f.label :pais %> <%= f.text_field :pais, :class => "form-control" %>
                   <%= f.label :ciudad %> <%= f.text_field :ciudad, :class => "form-control" %>
                   <%= f.label :logo %> <%= f.text_field :logo, :class => "form-control" %>
                  <hr>
                  <%= f.submit "Crear", :class => "btn btn-primary" %>
               
               </div>
               <div class="col-sm-6">
                  <%= f.label :email %> <%= f.text_field :email, :class => "form-control" %> 
                  <%= f.label :contacto %> <%= f.text_field :contacto, :class => "form-control" %>
                  <%= f.label :celular %> <%= f.text_field :celular, :class => "form-control" %>
                  <%= f.label :telefono %> <%= f.text_field :telefono, :class => "form-control" %>
                  <%= f.label :direccion %> <%= f.text_field :direccion, :class => "form-control" %>
               </div> 
               
                
               
            <% end %>          
         </div> <!--Panel-body -->
      </div>  <!--Panel-default -->
   </div> <!-- Col sm 6 -->

   
  

   <%= link_to "Inicio", root_path,:class => "btn btn-default" %>


</div>   <!-- Container -->

app/views/clients/show.html.erb
<%= render "layouts/menu" %>

<div class="container-fluid">
   <div class="col-sm-9">
         <div class="panel panel-default">
            <div class="panel-heading">
               <h2 class="panel-title text-left"><%= @client.name %> 
                  <%= link_to "Editar Cliente", edit_client_path(@client) , :class => "btn btn-default" %>
                  <%= link_to "Nuevo Kontest", new_client_kontest_path(@client) , :class => "btn btn-default" %> 
                  <%= link_to "Indice de clientes", clients_path , :class => "btn btn-default" %>
               </h2>   
            </div>
            <div class="panel-body">
               <div class="row">
                  <div class="col-sm-6">                     
                     <table class="table table-bordered">
                        <tr><th scope="row">Email:</th><td><%= @client.email %></td></tr>
                        <tr><th scope="row">Contacto:</th><td><%= @client.contacto   %> </td></tr>
                        <tr><th scope="row">Celular:</th><td><%= @client.celular   %> </td></tr>
                        <tr><th scope="row">Telefono:</th><td><%= @client.telefono   %> </td></tr>
                        <tr><th scope="row">Comentarios:</th><td><%= @client.comentarios   %> </td></tr>
                     </table>
                  </div> 
                  <div class="col-sm-6">                     
                     <table class="table table-bordered">
                        <tr><th scope="row">Direccion:</th><td><%= @client.direccion   %> </td></tr>
                        <tr><th scope="row">Pais:</th><td><%= @client.pais   %> </td></tr>
                        <tr><th scope="row">Ciudad:</th><td><%= @client.ciudad   %> </td></tr>
                        <tr><th scope="row">Logo:</th><td><%= @client.logo   %> </td></tr>
                     </table>
                  </div>
               </div>               
               
               
               <div class="row">              
                  <div class="col-sm-12"> 
                     <div class="panel panel-default">
                        <div class="panel-heading">Kontests</div>
                           <table class="table table-bordered">
                              <tr>
                                 <th>Id</th>
                                 <th>Codigo</th>
                                 <th>Premio</th>
                                 <th>Fecha Inicio</th>
                                 <th>Fecha Fin</th>
                                 <th>Ganadores Disponibles</th>
                                 <th>Total Codigos</th>
                                 <th>Usuarios Ganadores</th>
                                 <th>Codigos Registrados</th>
                              </tr>
                              <% if @kontests %>
                                 <% total_winner = 0 %>
                                 <% total_registered = 0 %>
                                 <% total_codigos = 0 %>
                                 <% @kontests.each do |kontest| %>     
                                 <!-- Next lines count winners and registered -->
                                    <% kontest.unicodes.each do |unicode| %>
                                          <% if unicode.user_id %>
                                             <% total_registered += 1 %>
                                             <% if unicode.winner %>
                                                <% total_winner += 1 %>
                                             <% end %>
                                          <% end %>
                                          <% total_codigos += 1 %>  
                                       <% end %>
                                 <!-- Below lines count winners and registered -->      
                                    <tr>
                                       <td><%= link_to kontest.id, kontest_path(kontest) %></td>
                                       <td><%= kontest.kontestcode %></td>
                                       <td><%= kontest.award %></td>
                                       <td><%= kontest.startdate.in_time_zone("Eastern Time (US & Canada)") %></td>
                                       <td><%= kontest.enddate.in_time_zone("Eastern Time (US & Canada)") %></td>
                                       <td><%= kontest.amountwinners %></td>
                                       <!-- <td><%= kontest.amountcodes %></td> -->
                                       <td><%= total_codigos %></td>
                                       <td><%= total_winner %></td>
                                       <td><%= total_registered %></td>
                                       <% total_winner = 0 %>
                                       <% total_registered = 0 %>
                                       <% total_codigos = 0 %>
                                    </tr>           
                                 <% end %>
                              <% end %>
                              
                           </table>         
                     </div> <!-- panel-default -->
                  </div> <!-- col-sm-12 -->
               </div>  <!-- row -->    
               
               
                 
                        
               

            </div> <!--Panel-body -->
      </div>  <!--Panel-default -->
   </div> <!-- Col sm 9 -->
      
   <div class="col-sm-3">
         <div class="panel panel-default">
            
                  <table class="table table-bordered">
                     <tr><th scope="row">Rset password enviado el: </th><td><%= @client.reset_password_sent_at   %></td></tr>
                     <tr><th scope="row">Recordatorio de clave el: </th><td><%= @client.remember_created_at   %></td></tr>
                     <tr><th scope="row">Ingresos: </th><td><%= @client.sign_in_count   %></td></tr>
                     <tr><th scope="row">Actual ingreso: </th><td><%= @client.current_sign_in_at   %></td></tr>
                     <tr><th scope="row">Ultimo ingreso:</th><td><%= @client.last_sign_in_at   %></td></tr>
                     <tr><th scope="row">IP: </th><td><%= @client.current_sign_in_ip   %></td></tr>
                     <tr><th scope="row">Ultimo IP: </th><td><%= @client.last_sign_in_ip   %></td></tr>
                     <tr><th scope="row">Creado el: </th><td><%= @client.created_at   %></td></tr>
                     <tr><th scope="row">Modificado el: </th><td><%= @client.updated_at   %> </td></tr>
                  </table>                       
      </div>  <!--Panel-default -->
   </div> <!-- Col sm 9 -->   

   
   
   
   


</div>