config/routes.rb
Rails.application.routes.draw do
 
  

  namespace :admin do
  get 'users/index'
  end

  namespace :admin do
  get 'users/show'
  end

  root to: "home#index"  

  mount RailsAdmin::Engine => '/dashboard', as: 'rails_admin'
  
  devise_for :admins

  namespace :admin do # Added this configuration so admin goes to admin/client when creating a new client instead of going to client home page
    resources :clients
    resources :users, only: [:index, :show]
  end

  devise_for :clients
  devise_for :users

  resources :clients do
    resources :kontests, shallow: true
  end

  get '/user/' => 'users#show', as: :user_show
  get '/user/edit' => 'users#edit',  as: :edit_user
  patch '/user' => 'users#update', as: :user_update
  get '/registercode' => 'users#registercode', as: :registercode
  post '/registercode' => 'users#addcode', as: :add_code
  get '/result' => 'users#result', as: :result
  get '/registeredcodes' => 'users#registeredcodes', as: :registeredcodes

  get '/homeadmin' => 'homeadmin#index', as: :indexadmin
  get '/homeuser' => 'homeuser#index', as: :indexuser
  get '/homeclient' => 'homeclient#index', as: :indexclient
  
  

  
    
  
  

end

app/models/kontest.rb
class Kontest < ActiveRecord::Base
   validates   :startdate, :enddate, :award, presence: true
   belongs_to :client
   has_many :unicodes, dependent: :destroy
   
   has_many :kontestusers
   has_many :users, :through => :kontestusers

   # private

   def generateCode
      self.kontestcode =  SecureRandom.hex(3)
      check_repeted_codes(self.kontestcode)
   end

   def check_repeted_codes(new_code)
      kontest = Kontest.where(kontestcode: new_code)
      if kontest.length != 0
         generateCode
      end
   end

end

app/controllers/kontests_controller.rb
class KontestsController < ApplicationController
  before_action :authenticate_admin!

  def index
   @kontests = Kontest.all
  end

  def show
   @kontest = Kontest.find params[:id]
   @client = @kontest.client
   @unicodes = Unicode.where(kontest_id: @kontest.id)
  end

  def new
   @kontest = Kontest.new
   @client = Client.find params[:client_id]
   @admin_email = current_admin.email
  end

  def create
   @kontest = Kontest.new kontest_params
   @client = Client.find params[:client_id]
   @kontest.client = @client
   @kontest.generateCode
   
   if @kontest.save
        @kontest.amountcodes.times do
          @code = Unicode.new  
          @code.setValues(@kontest)  
          @code.save
        end
      redirect_to kontest_path(@kontest)
   else
      render :new
   end
  end

  def edit
   @kontest = Kontest.find params[:id]
   @client = @kontest.client
   @admin = current_admin
  end

  def update
   @kontest = Kontest.find params[:id]
   if @kontest.update_attributes kontest_params
      redirect_to kontest_path(@kontest)
   else
      render :edit
   end
  end

  private

  def kontest_params
   params.require(:kontest).permit(:clientcode, :clientname, :startdate, :enddate, :admin, :award, :amountwinners, :amountcodes)
  end

end

app/helpers/kontests_helper.rb
module KontestsHelper
end

app/views/kontests/edit.html.erb
<br>

<% if @kontest.errors.any? %>
   <% @kontest.errors.full_messages.each do |error|%>
   <p class="text-danger">
      <%= error%>
   </p>
   <% end %>
<% end %>



<div class="container-fluid">
   
   <div class="col-sm-6">
      <div class="panel panel-default">
         <div class="panel-heading">
            <h3 class="panel-title">Editar Kontest</h3>
         </div>
         <div class="panel-body">
            <%= form_for [ @kontest] do |f| %>
               
               <%= f.label :clientname, "Nombre del Cliente" %> <%= f.text_field :admin, :value => @client.name, :disabled => true, :class => "form-control"  %>
               <%= f.label :admin, "Creado por: " %> <%= f.text_field :admin, :value => @admin.email, :disabled => true, :class => "form-control"  %>
               <%= f.label :amountwinners, "Cantidad de Ganadores" %> <%= f.text_field :amountwinners, :value => @kontest.amountwinners, :disabled => true, :class => "form-control"  %>
               <%= f.label :amountcodes, "Cantidad de Codigos" %> <%= f.text_field :amountcodes, :value => @kontest.amountcodes, :disabled => true, :class => "form-control"  %>
               <%= f.label :award, "Descripcion del Premio" %> <%= f.text_field :award, :class => "form-control"  %>
               <br>
               <%= f.label :startdate, "Fecha de Inicio" %> <%= f.date_select :startdate , {:order => [:day, :month, :year], :include_blank => true, :start_year => Date.current.year + 3, :end_year => Date.current.year,:use_month_names => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre','Diciembre']} ,:class => "form-control", :style => "width:50px; display: inline;" %>
               <br>
               <%= f.label :enddate, "Fecha de Finalizacion" %> <%= f.date_select :enddate , {:order => [:day, :month, :year], :include_blank => true, :start_year => Date.current.year + 3, :end_year => Date.current.year,:use_month_names => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre','Diciembre']} ,:class => "form-control", :style => "width:50px; display: inline;" %>

               <%= f.submit "Aceptar Cambios", :class => "btn btn-primary" %> 
               
            <% end %>
                
               
              
         </div> <!--Panel-body -->
      </div>  <!--Panel-default -->
   </div> <!-- Col sm 6 -->

   
  

   <%= link_to "Inicio", root_path,:class => "btn btn-default" %>


</div>   <!-- Container -->

app/views/kontests/index.html.erb
<h1>Kontests#index</h1>


<% @kontests.each do |kontest| %>
   <p> Nombre: <%= link_to kontest.clientname, kontest_path(kontest) %> - 
    Code: <%= kontest.clientcode %></p>
<% end %>

<li><%= link_to "Home", root_path, :class => "btn btn-default" %></li>
<li><%= link_to "Nuevo Kontest", new_kontest_path, :class => "btn btn-default" %></li>
<li><%= link_to "Administracion", "/admin" , :class => "btn btn-default" %></li>

app/views/kontests/new.html.erb
<br>

<% if @kontest.errors.any? %>
   <% @kontest.errors.full_messages.each do |error|%>
   <p class="text-danger">
      <%= error%>
   </p>
   <% end %>
<% end %>


<div class="container-fluid">
   
   <div class="col-sm-6">
      <div class="panel panel-default">
         <div class="panel-heading">
            <h3 class="panel-title">Crear Kontest</h3>
         </div>
         <div class="panel-body">
            
            <%= form_for [:client, @kontest] do |f| %>
               
              <%= f.label :clientname, "Nombre del Cliente" %> <%= f.text_field :clientname, :value => @client.name, :readonly => true, :class => "form-control"  %>
              <%= f.label :admin, "Creado por: " %> <%= f.text_field :admin, :value => @admin_email, :readonly => true , :class => "form-control"  %>
              <%= f.label :amountwinners, "Cantidad de Ganadores" %> <%= f.select :amountwinners, (1..300) , :class => "form-control"  %>
              <%= f.label :amountcodes, "Cantidad de Codigos" %> <%= f.select :amountcodes, [5,10,20,100,500,1500,3500,10000] , :class => "form-control"  %>

              <%= f.label :award, "Descripcion del Premio" %> <%= f.text_field :award , :class => "form-control"  %>
              <br>
              <%= f.label :startdate, "Fecha de Inicio" %> <%= f.date_select :startdate , {:order => [:day, :month, :year], :include_blank => true, :start_year => Date.current.year + 3, :end_year => Date.current.year,:use_month_names => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre','Diciembre']} ,:class => "form-control", :style => "width:50px; display: inline;"  %>
              <br>
              <%= f.label :enddate, "Fecha de Finalizacion" %> <%= f.date_select :enddate , {:order => [:day, :month, :year], :include_blank => true, :start_year => Date.current.year + 3, :end_year => Date.current.year,:use_month_names => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre','Diciembre']} ,:class => "form-control", :style => "width:50px; display: inline;" %>
               <br>
              <%= f.submit "Crear", :class => "btn btn-primary" %> 
               
            <% end %>            
                
               
              
         </div> <!--Panel-body -->
      </div>  <!--Panel-default -->
   </div> <!-- Col sm 6 -->

   
  

   <%= link_to "Inicio", root_path,:class => "btn btn-default" %>


</div>   <!-- Container -->

app/views/kontests/show.html.erb
<br>

<div class="container-fluid">
   <div class="col-sm-12">
         <div class="panel panel-default">
            <div class="panel-heading">
               <h2 class="panel-title text-left"><%= @client.name %> 
                  <%= link_to "Edit", edit_kontest_path(@kontest), :class => "btn btn-default" %>
                  <%= link_to "Cliente", client_path(@client), :class => "btn btn-default" %>
                  
               </h2>   
            </div>
            <div class="panel-body">
               <div class="row">
                  <div class="col-sm-6">                     
                     <table class="table table-bordered">
                        
                        <!-- Next lines count winners and registered -->
                        <% total_winner = 0 %>
                        <% total_registered = 0 %>
                        <% total_codigos = 0 %>
                           <% @kontest.unicodes.each do |unicode| %>
                                 <% if unicode.user_id %>
                                    <% total_registered += 1 %>
                                    <% if unicode.winner %>
                                       <% total_winner += 1 %>
                                    <% end %>
                                 <% end %>
                                 <% total_codigos += 1 %>  
                              <% end %>
                        <!-- Below lines count winners and registered -->  

                        <tr><th scope="row">Cliente: </th><td><%= @kontest.clientname %></td></tr>
                        <tr><th scope="row">Codigo del Kontest: </th><td><%= @kontest.kontestcode %></td></tr>
                        <tr><th scope="row">Creado por: </th><td><%= @kontest.admin %></td></tr>
                        <tr><th scope="row">Inicio: </th><td><%= @kontest.startdate.in_time_zone("Eastern Time (US & Canada)")  %></td></tr>
                        <tr><th scope="row">Finalizacion: </th><td><%= @kontest.enddate.in_time_zone("Eastern Time (US & Canada)")  %></td></tr>
                     </table>
                  </div> 
                  <div class="col-sm-6">                     
                     <table class="table table-bordered">
                        
                        <tr><th scope="row">Ganadores Disponibles: </th><td><%= @kontest.amountwinners %></td></tr>
                        <tr><th scope="row">Usuarios Ganadores: </th><td><%= total_winner %></td></tr>
                        <tr><th scope="row">Total Codigos: </th><td><%= total_codigos %></td></tr>
                        <tr><th scope="row">Codigos Registrados: </th><td><%= total_registered %></td></tr>
                        <tr><th scope="row">Premio: </th><td><%= @kontest.award %></td></tr>
                     </table>
                  </div>
               </div>               
               
               
               <div class="row">              
                  <div class="col-sm-12"> 
                     <div class="panel panel-default">
                        <div class="panel-heading">Unicodes</div>
                           <table class="table table-bordered">
                              <tr>
                                 <th>Id</th>
                                 <th>Kontest Id</th>
                                 <th>Codigo Kontest</th>
                                 <th>Secuencia</th>
                                 <th>Ganador</th>
                                 <th>Id Usuario</th>
                                 <th>Fecha Registro</th>
                              </tr>
                              
                                  <% @unicodes.each do |unicode| %>    
                                    <tr>
                                       <td><%= unicode.id %></td>
                                       <td><%= unicode.kontest_id %></td>
                                       <td><%= unicode.kontestcode %></td>
                                       <td><%= unicode.secuence %></td>
                                       <td><%= unicode.winner %></td>
                                       <td><%= unicode.user_id %></td>
                                       <% if unicode.registrationdate %>
                                          <td><%= unicode.registrationdate.in_time_zone("Eastern Time (US & Canada)")  %></td>
                                       <% else %>
                                          <td><%= unicode.registrationdate %></td>
                                                
                                       <% end %>
                                    </tr>           
                                 <% end %>
                              
                              
                           </table>         
                     </div> <!-- panel-default -->
                  </div> <!-- col-sm-12 -->
               </div>  <!-- row -->    
               
               
                 
                        
               

            </div> <!--Panel-body -->
      </div>  <!--Panel-default -->
   </div> <!-- Col sm 9 -->


</div> <!-- Container -->